name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Hello world       # Name of step
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'

    - name: Build dotnet
      run: dotnet build  

    - name: Install and run npm
      working-directory: DotnetTemplate.web
      run: |
        npm install     
        npm run build

    - name: Test dotnet
      run: dotnet test

    - name: npm tests and lint
      working-directory: DotnetTemplate.web
      run: |
        npm t
        run npm lint



  